# Generated by Django 3.2.7 on 2021-09-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Slug to forward from', unique=True)),
                ('stats_enabled', models.BooleanField(default=True, help_text='Enable statistics')),
                ('hits', models.PositiveIntegerField(default=0, help_text='Number of hits')),
                ('target', models.URLField(help_text='URL to forward to')),
                ('permanent', models.BooleanField(default=False, help_text='Should the redirect be permanent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Slug to forward from', unique=True)),
                ('stats_enabled', models.BooleanField(default=True, help_text='Enable statistics')),
                ('hits', models.PositiveIntegerField(default=0, help_text='Number of hits')),
                ('content', models.TextField(help_text='Content of static page')),
                ('content_type', models.TextField(default='text/plain', help_text='Content Type of static page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
