# Generated by Django 3.2.7 on 2021-12-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='target',
            field=models.URLField(help_text='URL to forward to', max_length=1000),
        ),
    ]
