# Generated by Django 3.2.18 on 2023-04-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tus', '0002_alter_shorturl_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='permanent',
            field=models.BooleanField(default=False, help_text='Should the redirect be permanent and use <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301" target="_blank" rel="noopener noreferer">HTTP 301</a> instead of <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302" target="_blank" rel="noopener noreferer">HTTP 302</a>?'),
        ),
    ]
